### ISSUE TITLE
Final review and publish on themeisle

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/naturelle#12]

**Comment by rodica-andronache** [comment]
- [ ] font is different then PSD
- [ ] pirate forms on contact page http://prntscr.com/ckob6t
- [ ] phone number is not italic in the PSD http://prntscr.com/ckoct8
- [ ] search icon is missing in header , like in the PSD 
- [ ] big space in footer , when copyrigh is missing, http://prntscr.com/ckoh3p different then the PSD
- [ ] powered by link in footer has different color then the psd
- [ ] posted on is different http://prntscr.com/ckoj4a , color and the categories should be upercase
- [ ] in the design, the comments form has placeholders, not labels http://prntscr.com/ckojza

**Comment by rodica-andronache** [comment]
@claudiuvertistudio are this fixed?
- font is different then PSD
- big space in footer , when copyrigh is missing, http://prntscr.com/ckoh3p different then the PSD
For me , it's not the same. what do you think?

**Comment by claudiuvertistudio** [comment]
font is not different then PSD
