### ISSUE TITLE
big title issues

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/naturelle#19]
- [x] can we disable the small logo by default/on demo ?
- [x] Can we disable the subtitle by default/ on demo ?
- [x] Can we make sure that the CTA button looks like the psd ?
- [x] Can we set the background image from psd ?

cc @rodica-andronache

**Comment by rodica-andronache** [comment]
@ineagu to disable the default values in the theme,we  would need to override the section file. I wouldn't do that. what you think? On demo I disabled the small logo and subtitle.

**Comment by rodica-andronache** [comment]
For the first two tasks, we need to wait for the Llorix One Lite update, that adds filters for those default options

**Comment by rodica-andronache** [comment]
llorix one lite is updated, so the filters should be there now
