### ISSUE TITLE
our services

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/naturelle#20]
Do we support the our services section ?

Can we show it on demo and make it work like the psd ? https://www.dropbox.com/s/u3f1o37670199qh/Screenshot%202016-10-07%2013.25.50.png?dl=0

cc @rodica-andronache

**Comment by rodica-andronache** [comment]
yes, it's added with Llorix One Companion. I added the section ,and added the content as in psd

@claudiuvertistudio can you please have a look at the design, and make it the same

**Comment by claudiuvertistudio** [comment]
looks well
