### ISSUE TITLE
our story section

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/naturelle#21]
@rodica-andronache can we have same typography like in the demo and allow users to add a button there ?

Can we use same text + image as psd ?

https://www.dropbox.com/s/avvjn964jr2bxe0/Screenshot%202016-10-07%2013.26.52.png?dl=0

**Comment by rodica-andronache** [comment]
- [ ] Add the image from psd, and add it on the demo page

- [ ] Add an option for a button in customizer, in the About section http://prntscr.com/cqwpi6
