### ISSUE TITLE
logos section

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/naturelle#24]
@rodica-andronache can we show the logos section like in the psd : https://www.dropbox.com/s/gvlhq9grobadv4e/Screenshot%202016-10-07%2013.31.20.png?dl=0 ?

**Comment by rodica-andronache** [comment]
- [ ] Add on demo, the images from PSD in the logos section http://prntscr.com/cqwhy4

- [ ] Add an option, in Customizer in the Logos bar section, for a title http://prntscr.com/cqwi8p
