### ISSUE TITLE
Aranjat demo 

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/naturelle#49]
@claudiuvertistudio poti te rog sa te mai uiti pe demo, ca pare ca s-au pierdut ceva setari /texte gen logo-ul si alte texte unde acum e lorem ipsum, si sa-l aranjezi https://demo.themeisle.com/naturelle/

**Comment by claudiuvertistudio** [comment]
eu pot, dar daca se pierde din nou? ca asta ar fi a 3-a oara cand aranjez demo-ul la naturelle

**Comment by ineagu** [comment]
probabil e mai ok sa investigam de ce sau pierdut, si unde sunt / ce sa intamplat ? nu are sens sa il tot refacem si el sa se strice
