### ISSUE TITLE
[Naturelle PRO] Demo

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/naturelle#51]
https://demo.themeisle.com/naturelle-pro/

Also, if you notice problems with the theme, you can report them here

**Comment by claudiuvertistudio** [comment]
1. About us -> Learn more Button => it doesn't appear
2. the icon from our services are too big

**Comment by rodica-andronache** [comment]
@abaicus besides the problem reported by Claudiu, which Cristi will try to fix, can you please check the demo to see if it's ok to be published?

**Comment by abaicus** [comment]
@rodica-andronache I think it looks good. Made just some small changes.
