### ISSUE TITLE
About section button not working

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/naturelle#54]
@rodica-andronache I tried an external link, nothing happens when clicking

**Comment by UVLabs** [comment]
+1

**Comment by cristian-ungureanu** [comment]
This was resolved here https://github.com/Codeinwp/parallax-one-plus/issues/141

**Comment by girl0000** [comment]
I have made all updates, and tried an external link again, but nothing happens when clicking.

@cristian-ungureanu: I can not open your link.

**Comment by UVLabs** [comment]
@girl0000 it seems the patch has been made but just not released @cristian-ungureanu you added the commit to the plus plugin doesn't the lite version also have this issue?

**Comment by rodica-andronache** [comment]
Hi @girl0000 ,

We just released an update for both the free and pro versions. Can you please update and let me know if everything is ok?

Thank you,
Rodica

**Comment by girl0000** [comment]
Sorry for my late feedback. I was on vacation.

I can now use external links in my free version. Thanks a lot!

**Comment by rodica-andronache** [comment]
Hi @girl0000 ,

I'm really glad to hear everything is ok now.
If you are happy with the theme or our support you can always leave us a review here https://wordpress.org/support/theme/naturelle/reviews/#new-post . We would really appreciate it.

Thank you,
Rodica
